/* DefineGraph.h */
#ifndef __VALUES__
#define __VALUES__

#include <time.h>
#include <MLV/MLV_all.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>


#define PI 3.14159

/* Team entity */
#define ALLY_CLAN 0
#define ENNEMY_CLAN 1
#define ITEM_CLAN 30

/* Main type entity */
#define SHOT 7
#define ENNEMY 1
#define BONUS 30

/* Type entity */
#define NONE -1
#define SHIP 0
#define SBIRE 1
#define SINUS 2
#define SNIPER 3
#define BOMBER 4
#define GATLING 5
#define COMET 6
#define SHIP_SHOT 7
#define SBIRE_SHOT 8
#define SNIPER_SHOT 9
#define SINUS_SHOT 10
#define GATLING_SHOT 11
typedef enum bonus_type {
  SHIELD = 12, HEAL = 13, NITRO = 14, TRIPLE_SHOT = 15, NOT_A_BONUS = 16
} Bonus_type;
#define TANK 17
#define BOSS 18

/* Stat entity */

#define HP_BOSS 50
#define VELOCITY_BOSS (0.1 * COEFF_RESOLUTION)
#define COOLDOWN_BOSS 10
#define DAMAGE_BOSS 2

#define HP_TANK 8
#define VELOCITY_TANK (0.5 * COEFF_RESOLUTION)
#define COOLDOWN_TANK 50
#define DAMAGE_TANK 1

#define HP_SBIRE_SHOT 1
#define VELOCITY_SBIRE_SHOT (4 * COEFF_RESOLUTION)
#define COOLDOWN_SBIRE_SHOT 0
#define DAMAGE_SBIRE_SHOT 1
#define DIRECTION_SBIRE_SHOT NONE

#define HP_GATLING_SHOT 1
#define VELOCITY_GATLING_SHOT (5 * COEFF_RESOLUTION)
#define COOLDOWN_GATLING_SHOT 0
#define DAMAGE_GATLING_SHOT 1
#define DIRECTION_GATLING_SHOT NONE

#define HP_SNIPER_SHOT 1
#define VELOCITY_SNIPER_SHOT (8 * COEFF_RESOLUTION)
#define COOLDOWN_SNIPER_SHOT 0
#define DAMAGE_SNIPER_SHOT 1
#define DIRECTION_SNIPER_SHOT NONE

#define HP_SINUS_SHOT 1
#define VELOCITY_SINUS_SHOT (2 * COEFF_RESOLUTION)
#define COOLDOWN_SINUS_SHOT 100
#define DAMAGE_SINUS_SHOT 1
#define DIRECTION_SINUS_SHOT NONE

#define HP_SHIP_SHOT 1
#define VELOCITY_SHIP_SHOT (15 * COEFF_RESOLUTION)
#define COOLDOWN_SHIP_SHOT 0
#define DAMAGE_SHIP_SHOT 1
#define DIRECTION_SHIP_SHOT (-PI/2)

#define HP_SBIRE 1
#define VELOCITY_SBIRE (1 * COEFF_RESOLUTION)
#define COOLDOWN_SBIRE 50
#define DAMAGE_SBIRE 1

#define HP_SINUS 3
#define VELOCITY_SINUS (1 * COEFF_RESOLUTION)
#define COOLDOWN_SINUS 50
#define DAMAGE_SINUS 1

#define HP_SNIPER 1
#define VELOCITY_SNIPER (2 * COEFF_RESOLUTION)
#define COOLDOWN_SNIPER 50
#define DAMAGE_SNIPER 1

#define HP_BOMBER 1
#define VELOCITY_BOMBER (2 * COEFF_RESOLUTION)
#define COOLDOWN_BOMBER 0
#define DAMAGE_BOMBER 2
#define RANGE_SIZE_BOMBER (WIDTH / 2)

#define HP_GATLING 3
#define VELOCITY_GATLING (2 * COEFF_RESOLUTION)
#define COOLDOWN_GATLING 50
#define DAMAGE_GATLING 1

#define HP_COMET 3
#define VELOCITY_COMET (2 * COEFF_RESOLUTION)
#define COOLDOWN_COMET 0
#define DAMAGE_COMET 1

#define SHIP_X (WIDTH / 2)
#define SHIP_Y ((3 * HEIGHT) / 4)
#define SHIP_HP 10
#define SHIP_VELOCITY (5 * COEFF_RESOLUTION)
#define SHIP_COOLDOWN 5
#define SHIP_DAMAGE 1
#define INERTIE_SCALE_SHIP_Z (0.3 * COEFF_RESOLUTION)
#define INERTIE_SCALE_SHIP_S (0.3 * COEFF_RESOLUTION)
#define INERTIE_SCALE_SHIP_Q (0.3 * COEFF_RESOLUTION)
#define INERTIE_SCALE_SHIP_D (0.3 * COEFF_RESOLUTION)
#define MAX_INERTIE_SHIP (10 * COEFF_RESOLUTION)

#define HITBOX_SHIP (10 * COEFF_RESOLUTION)
#define HITBOX_SBIRE (15 * COEFF_RESOLUTION)
#define HITBOX_SINUS (21 * COEFF_RESOLUTION)
#define HITBOX_SNIPER (16 * COEFF_RESOLUTION)
#define HITBOX_BOMBER (12 * COEFF_RESOLUTION)
#define HITBOX_SHIP_SHOT (12 * COEFF_RESOLUTION)
#define HITBOX_SBIRE_SHOT (7 * COEFF_RESOLUTION)
#define HITBOX_SINUS_SHOT (12 * COEFF_RESOLUTION)
#define HITBOX_SNIPER_SHOT (8 * COEFF_RESOLUTION)
#define HITBOX_GATLING (16 * COEFF_RESOLUTION)
#define HITBOX_COMET (28 * COEFF_RESOLUTION)
#define HITBOX_GATLING_SHOT (8 * COEFF_RESOLUTION)
#define HITBOX_TANK (24 * COEFF_RESOLUTION)
#define HITBOX_BOSS (60 * COEFF_RESOLUTION)


/* Chance spawn entity */
#define MIN_CHANCE_SPAWN_ENNEMY 0
#define MAX_CHANCE_SPAWN_ENNEMY 100

/*Difficulty (quantity)*/

#define SPAWN_CHANCE_ENNEMY 2

/*/CHANCE_ENNEMY*/
#define CHANCE_SBIRE 50
#define CHANCE_SINUS (10 + CHANCE_SBIRE)
#define CHANCE_SNIPER (10 + CHANCE_SINUS)
#define CHANCE_BOMBER (5 + CHANCE_SNIPER)
#define CHANCE_GATLING (5 + CHANCE_BOMBER)
#define CHANCE_COMET (3 + CHANCE_GATLING)
#define CHANCE_ENNEMY CHANCE_COMET


/* Star stat */
#define MAX_STAR 300
#define MAX_SIZE_STARS 8
#define MIN_SIZE_STARS 2
#define MAX_SPEED_STARS 2
#define TRANSPARENCY_STARS 4
#define TRANSPARENCY_STARS_FACTOR 60
#define STAR_RAND 5

/* Bonus stat */
#define NB_BONUS 4
#define TIME_HEAL 1
#define TIME_SHIELD (FREQUENCY * 5) /*seconds*/
#define TIME_TRIPLE_SHOT (FREQUENCY * 8) /*seconds*/
#define TIME_NITRO (FREQUENCY * 10) /*seconds*/
#define SPRITE_BONUS_SIZE 10
#define HITBOX_BONUS_SIZE 10
#define NITRO_SPEED_FACTOR 2


/*Parsing*/
#define MAXENNEMIES 512
#define SIZETOKENMAX 5
#define SIZEOFLINEMAX 50

#define MAX_LEVEL 5

#endif
