#ifndef __GRAPHICVALUES__
#define __GRAPHICVALUES__

#define W (MLV_get_desktop_width())
#define H (MLV_get_desktop_height())

#define WIDTH ((float) W)
#define HEIGHT ((float) H)
#define MULTIPLICATEUR 1

#define COEFF_RESOLUTION ((WIDTH/HEIGHT) * MULTIPLICATEUR)

#define FREQUENCY 60

#define CLOSE_BUTTON_RAY 50
#define CLOSE_BUTTON_X (WIDTH - CLOSE_BUTTON_RAY)
#define CLOSE_BUTTON_Y (0 + CLOSE_BUTTON_RAY)
#define PLAY_BUTTON_X1 (WIDTH/4)
#define PLAY_BUTTON_Y1 (HEIGHT/4)
#define PLAY_BUTTON_X2 (WIDTH/2 + WIDTH/4)
#define PLAY_BUTTON_Y2 (HEIGHT/2)

#define LEVEL_BUTTON_X1 (WIDTH/4)
#define LEVEL_BUTTON_Y1 (PLAY_BUTTON_Y1 + (HEIGHT/3))
#define LEVEL_BUTTON_X2 (WIDTH/2 + WIDTH/4)
#define LEVEL_BUTTON_Y2 (PLAY_BUTTON_Y2 + (HEIGHT/3))

#define SPRITE_SIZE_SHIP (32 * COEFF_RESOLUTION)
#define SPRITE_SIZE_SBIRE (32 * COEFF_RESOLUTION)
#define SPRITE_SIZE_SINUS (48 * COEFF_RESOLUTION)
#define SPRITE_SIZE_SNIPER (48 * COEFF_RESOLUTION)
#define SPRITE_SIZE_BOMBER (16 * COEFF_RESOLUTION)
#define SPRITE_SIZE_SHIP_SHOT (16 * COEFF_RESOLUTION)
#define SPRITE_SIZE_SBIRE_SHOT (16 * COEFF_RESOLUTION)
#define SPRITE_SIZE_SINUS_SHOT (24 * COEFF_RESOLUTION)
#define SPRITE_SIZE_SNIPER_SHOT (8 * COEFF_RESOLUTION)
#define SPRITE_SIZE_GATLING (56 * COEFF_RESOLUTION)
#define SPRITE_SIZE_COMET (64 * COEFF_RESOLUTION)
#define SPRITE_SIZE_GATLING_SHOT (16 * COEFF_RESOLUTION)
#define SPRITE_SIZE_HEAL (56 * COEFF_RESOLUTION)
#define SPRITE_SIZE_SHIELD (56 * COEFF_RESOLUTION)
#define SPRITE_SIZE_TRIPLE_SHOT (56 * COEFF_RESOLUTION)
#define SPRITE_SIZE_NITRO (56 * COEFF_RESOLUTION)
#define SPRITE_TANK (48 * COEFF_RESOLUTION)
#define SPRITE_BOSS (138 * COEFF_RESOLUTION)


#define ARENA 0
#define LEVELS 1
#define HOWTOPLAY 2
#define CLOSE 3
#define ARENAGLOW 4
#define LEVELSGLOW 5
#define HOWTOPLAYGLOW 6
#define CLOSEGLOW 7
#define HOWTOPLAYINTERFACE 8

#define X_ARENA (W / 5)
#define Y_ARENA (H / 3)
#define X_LEVELS (W / 5)
#define Y_LEVELS (Y_ARENA + 84)
#define X_HOWTOPLAY (W / 5)
#define Y_HOWTOPLAY (Y_LEVELS + 84)
#define X_CLOSE (W - (28 * COEFF_RESOLUTION * 2))
#define Y_CLOSE ((0) * COEFF_RESOLUTION)
#define X_HOWTOPLAYINTERFACE 0
#define Y_HOWTOPLAYINTERFACE 0

#define WIDTH_ARENA (144 * COEFF_RESOLUTION * 1.2)
#define HEIGHT_ARENA (28 * COEFF_RESOLUTION * 1.2)
#define WIDTH_LEVELS (144 * COEFF_RESOLUTION * 1.2)
#define HEIGHT_LEVELS (28 * COEFF_RESOLUTION * 1.2)
#define WIDTH_HOWTOPLAY (266 * COEFF_RESOLUTION * 1.2)
#define HEIGHT_HOWTOPLAY (28 * COEFF_RESOLUTION * 1.2)
#define WIDTH_CLOSE (28 * COEFF_RESOLUTION * 2)
#define HEIGHT_CLOSE (28 * COEFF_RESOLUTION * 2)
#define WIDTH_HOWTOPLAYINTERFACE W
#define HEIGHT_HOWTOPLAYINTERFACE H

#endif
